// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChb5feddeF6a-koVd_H1nUEMGZUPWGL3g',
    appId: '1:1060942941845:web:4238f8daa64df431a1959c',
    messagingSenderId: '1060942941845',
    projectId: 'notes-20e21',
    authDomain: 'notes-20e21.firebaseapp.com',
    storageBucket: 'notes-20e21.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD06jqqdeH11vr2YA4ytwc3XkvJ_Wezk_4',
    appId: '1:1060942941845:android:9eef4934fb657b4da1959c',
    messagingSenderId: '1060942941845',
    projectId: 'notes-20e21',
    storageBucket: 'notes-20e21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6sPQzQH2er1Lenqzlfp4hm0EFeX-cBpA',
    appId: '1:1060942941845:ios:dc023ad036a6f31fa1959c',
    messagingSenderId: '1060942941845',
    projectId: 'notes-20e21',
    storageBucket: 'notes-20e21.appspot.com',
    iosBundleId: 'com.mosaad.not',
  );
}
